spring.datasource.url=jdbc:h2:file:./data/mydatabase;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.envers.autoRegisterListeners=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
#Enable SQL initialization
spring.sql.init.mode=never
spring.sql.init.data-locations=classpath:data.sql
ban.word.threshold=4
#Retry
resilience4j.retry.instances.getPostById.max-attempts=2
resilience4j.retry.instances.getPostById.wait-duration=2s
resilience4j.retry.instances.getAllSatellites.max-attempts=2
resilience4j.retry.instances.getAllSatellites.wait-duration=3s
resilience4j.retry.instances.getAllPosts.max-attempts=3
resilience4j.retry.instances.getAllPosts.wait-duration=4s
#Circuit Breaker
resilience4j.circuitbreaker.instances.satelliteCircuitBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.satelliteCircuitBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.satelliteCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.satelliteCircuitBreaker.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.satelliteCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.postCircuitBreaker.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.postCircuitBreaker.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.postCircuitBreaker.sliding-window-size=20
resilience4j.circuitbreaker.instances.postCircuitBreaker.wait-duration-in-open-state=20s
resilience4j.circuitbreaker.instances.postCircuitBreaker.permitted-number-of-calls-in-half-open-state=5
resilience4j.circuitbreaker.instances.getAllPostsCircuitBreaker.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.getAllPostsCircuitBreaker.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.getAllPostsCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.getAllPostsCircuitBreaker.wait-duration-in-open-state=20s
resilience4j.circuitbreaker.instances.getAllPostsCircuitBreaker.permitted-number-of-calls-in-half-open-state=3
#Bulkhead
resilience4j.thread-pool-bulkhead.instances.satelliteBulkhead.core-thread-pool-size=5
resilience4j.thread-pool-bulkhead.instances.satelliteBulkhead.max-thread-pool-size=10
resilience4j.thread-pool-bulkhead.instances.satelliteBulkhead.queue-capacity=20