#app
server.port=8086
spring.application.name=TECO
server.servlet.context-path=/api
#oracle Datasource
spring.datasource.url=jdbc:oracle:thin:@DB3RH:1521/setadidevdb.tamin.org
spring.datasource.username=tco
spring.datasource.password=tco
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
oauth2.jwks-uri=http://account-test.tamin.ir:9090/auth/.well-known/jwks.json
origins=http://172.16.15.62:4205,http://172.16.15.12:4202,http://172.16.15.66:4203,http://172.16.15.69:4201,http://172.16.15.62:4201,http://localhost:4200,http://172.16.15.54:4205,http://172.16.15.66:4205,http://172.16.15.12:4204
oauth.client_id=27295837720a55045d706a5584387337
oauth.client_secret=0d8333216a17890b043d187d1b6c23136a7b538c44305e79470c20691c73760d
oauth.token_endpoint=http://account-test.tamin.ir:9090/auth/server/token
user.base=http://account-test.tamin.ir:9091/portal/api/v2.0/users
oauth.audience_uri=http://172.16.15.54:8082/api
server.tomcat.relaxed-query-chars=[,],{,},|,",'
server.tomcat.relaxed-path-chars=[,],{,},|,",'
spring.messages.encoding=UTF-8
# Datasource Information
spring.session.jdbc.initialize-schema=always
spring.data.jdbc.dialect=oracle
spring.datasource.hikari.auto-commit=false
spring.batch.jdbc.isolation-level-for-create=default
spring.datasource.hikari.maximum-pool-size=5
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.id=teco
server.error.include-message=always
server.error.include-binding-errors=always
